# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Publications
    url: /publication/
    weight: 12
  - name: Talks
    url: /talks/
    weight: 13
  - name: News
    url: /news/
    weight: 15
  - name: Experience
    url: experience/
    weight: 11
  - name: The LabOratory
    url: /laboratory/
    weight: 14
  #- name: Teaching
  #  url: teaching/
  #  weight: 14
  #- name: Projects
  #  url: projects/
  #  weight: 30
